#ifndef MQTT_MODULE_MQTT_CONFIG_H
#define MQTT_MODULE_MQTT_CONFIG_H

#include <Arduino.h>

#ifndef MQTT_MAX_TOPIC_LENGTH
#define MQTT_MAX_TOPIC_LENGTH 60
#endif

#ifndef MQTT_MAX_MESSAGE_LENGTH
#define MQTT_MAX_MESSAGE_LENGTH 40
#endif

const uint8_t MQTT_MAX_LEN_TOPIC {MQTT_MAX_TOPIC_LENGTH};
const uint8_t MQTT_MAX_LEN_MESSAGE {MQTT_MAX_MESSAGE_LENGTH};

const uint8_t MAX_LEN_URL {150};

const char CHANNEL_SUBSCRIBE[] PROGMEM {MQTT_CLIENT_NAME "/subscribe"};
const char CHANNEL_INFO[] PROGMEM {MQTT_CLIENT_NAME "/%s/%d"};
const char CHANNEL_SET_JSON[] PROGMEM {MQTT_CLIENT_NAME "/set/json"};
const char CHANNEL_KEEP_ALIVE[] PROGMEM {MQTT_CLIENT_NAME "/keep-alive"};
const char CHANNEL_MQTT_TO_NRF_NETWORK[] PROGMEM {"nrfNetwork/#"};

const uint16_t DEFAULT_PIN_READ_TIME = 30000;
const uint8_t MAX_LEN_JSON_MESSAGE {120};

#endif
