#ifndef RADIO_ENCRYPTED_RADIO_ENCRYPTED_CONFIG_H
#define RADIO_ENCRYPTED_RADIO_ENCRYPTED_CONFIG_H

#include <Arduino.h>

#ifndef NRF_RADIO_CHANNEL
#define NRF_RADIO_CHANNEL 102
#endif
#ifndef ENCRYPTION_MAX_USER_DATA_LENGTH
#define ENCRYPTION_MAX_USER_DATA_LENGTH 6
#endif
#ifndef ENCRYPTION_MAX_TAG_LENGTH
#define ENCRYPTION_MAX_TAG_LENGTH 5
#endif

const uint8_t ENCRYPTION_CIPHER_LENGTH {ENCRYPTION_MAX_USER_DATA_LENGTH};
const uint8_t ENCRYPTION_VECTOR_LENGTH {16};
const uint8_t ENCRYPTION_TAG_LENGTH {ENCRYPTION_MAX_TAG_LENGTH};
const uint8_t ENCRYPTION_KEY_LENGTH {16};

const uint16_t MESH_TIMEOUT {5000};

const uint8_t RADIO_CHANNEL {NRF_RADIO_CHANNEL};

#include "Message.h"

#endif
